services:
  github_repos_observer_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${MY_IMAGE:-github-repos-observer-backend:latest}
    env_file:
      - env/prod.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    ports:
      - '8080:8080'
    platform: linux/amd64
    networks:
      - github_repos_observer_network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/actuator/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  github_repos_observer_network:
    external: true
